[display]
cell_output = "above"
theme = "light"
dataframes = "rich"
default_width = "medium"
code_editor_font_size = 14

[keymap]
preset = "default"
[keymap.overrides]
"cell.signatureHelp" = "Ctrl-:"
"global.toggleTerminal" = "Ctrl-²"

[ai]
rules = ""
[ai.open_ai]

[ai.google]

[ai.anthropic]

[language_servers.pylsp]
enable_pylint = false
enabled = true
enable_flake8 = false
enable_ruff = true
enable_pyflakes = false
enable_pydocstyle = false
enable_mypy = true

[package_management]
manager = "pip"

[experimental]

[snippets]
include_default_snippets = true
custom_paths = []

[server]
browser = "default"
follow_symlink = false

[runtime]
auto_reload = "lazy"
auto_instantiate = false
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
watcher_on_save = "lazy"
on_cell_change = "autorun"

[completion]
activate_on_typing = false
copilot = false

[formatting]
line_length = 120

[save]
format_on_save = true
autosave_delay = 1000
autosave = "after_delay"
